// mockUserDB.js
export const users = [
  {
    name: "Mori",
    email: "user@example.com",
    password: "user123",
    role: "menber",
    phone: "0932766444",
    address: "台南市245號中正路",
    image: "/BuyFlow/user/user-menber.svg",
  },
  {
    name: "Alice",
    staff_id: "admin123",
    email: "admin@example.com",
    password: "admin123",
    role: "admin",
    phone: "0945805042",
    address: "高雄市295號建國路",
    image: "/BuyFlow/user/user-menber.svg",
  },
  {
    name: "Bob",
    staff_id: "Bob_staff321",
    email: "staff@example.com",
    password: "staff321",
    role: "staff",
    phone: "0970723080",
    address: "台中市109號中山路",
    image: "/BuyFlow/user/user-menber.svg",
  },
  {
    name: "User1",
    email: "user1@example.com",
    password: "user1pass",
    role: "menber",
    phone: "0963314629",
    address: "新北市298號復興路",
    image: "/BuyFlow/user/user-menber.svg",
  },
  {
    name: "User2",
    email: "user2@example.com",
    password: "user2pass",
    role: "menber",
    phone: "0916775189",
    address: "高雄市94號中正路",
    image: "/BuyFlow/user/user-menber.svg",
  },
  {
    name: "User3",
    email: "user3@example.com",
    password: "user3pass",
    role: "menber",
    phone: "0929071411",
    address: "台南市176號和平路",
    image: "/BuyFlow/user/user-menber.svg",
  },
  {
    name: "User4",
    email: "user4@example.com",
    password: "user4pass",
    role: "menber",
    phone: "0989224964",
    address: "台北市260號民權路",
    image: "/BuyFlow/user/user-menber.svg",
  },
  {
    name: "Staff1",
    staff_id: "staff1_id",
    email: "staff1@example.com",
    password: "staff1pass",
    role: "staff",
    phone: "0922665660",
    address: "新北市26號民權路",
    image: "/BuyFlow/user/user-menber.svg",
  },
  {
    name: "Staff2",
    staff_id: "staff2_id",
    email: "staff2@example.com",
    password: "staff2pass",
    role: "staff",
    phone: "0971231619",
    address: "台南市26號和平路",
    image: "/BuyFlow/user/user-menber.svg",
  },
  {
    name: "Staff3",
    staff_id: "staff3_id",
    email: "staff3@example.com",
    password: "staff3pass",
    role: "staff",
    phone: "0932634680",
    address: "新北市197號和平路",
    image: "/BuyFlow/user/user-menber.svg",
  },
];
